-- H2는 PostgreSQL pgvector V3를 실행할 수 없다. 학습 흐름 테스트에는 V4~V18 관계형 스키마만 보완한다.
ALTER TABLE learning_question ADD COLUMN option_explanations TEXT NOT NULL DEFAULT '[]';
CREATE TABLE question_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    feedback_type VARCHAR(64) NOT NULL,
    comment VARCHAR(500),
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_question_feedback_question UNIQUE (question_id),
    CONSTRAINT fk_question_feedback_question FOREIGN KEY (question_id) REFERENCES learning_question(id)
);

CREATE TABLE learning_roadmap (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    duration_weeks INTEGER NOT NULL,
    questions_per_week INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    source_type VARCHAR(32) NOT NULL DEFAULT 'WEEKLY',
    description TEXT,
    definition_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE learning_roadmap_week (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id BIGINT NOT NULL,
    week_number INTEGER NOT NULL,
    topic VARCHAR(255) NOT NULL,
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    planned_questions INTEGER NOT NULL,
    CONSTRAINT uk_learning_roadmap_week UNIQUE (roadmap_id, week_number),
    CONSTRAINT fk_learning_roadmap_week_roadmap FOREIGN KEY (roadmap_id) REFERENCES learning_roadmap(id)
);

ALTER TABLE learning_quiz ADD COLUMN roadmap_id BIGINT;
ALTER TABLE learning_quiz ADD CONSTRAINT fk_learning_quiz_roadmap
    FOREIGN KEY (roadmap_id) REFERENCES learning_roadmap(id) ON DELETE SET NULL;

CREATE TABLE learning_roadmap_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id BIGINT NOT NULL,
    step_key VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    topic VARCHAR(255) NOT NULL,
    question_target INTEGER NOT NULL,
    step_order INTEGER NOT NULL,
    major_topic_key VARCHAR(64) NOT NULL,
    major_topic_title VARCHAR(255) NOT NULL,
    major_topic_description TEXT,
    major_topic_topic VARCHAR(255) NOT NULL,
    subtopic_key VARCHAR(48),
    subtopic_title VARCHAR(255),
    advance_confirmed_at TIMESTAMP,
    CONSTRAINT uk_learning_roadmap_step_key UNIQUE (roadmap_id, step_key),
    CONSTRAINT uk_learning_roadmap_step_order UNIQUE (roadmap_id, step_order),
    CONSTRAINT fk_learning_roadmap_step_roadmap FOREIGN KEY (roadmap_id) REFERENCES learning_roadmap(id) ON DELETE CASCADE
);

CREATE TABLE learning_roadmap_step_dependency (
    step_id BIGINT NOT NULL,
    prerequisite_step_id BIGINT NOT NULL,
    PRIMARY KEY (step_id, prerequisite_step_id),
    CONSTRAINT fk_roadmap_dependency_step FOREIGN KEY (step_id) REFERENCES learning_roadmap_step(id) ON DELETE CASCADE,
    CONSTRAINT fk_roadmap_dependency_prerequisite FOREIGN KEY (prerequisite_step_id) REFERENCES learning_roadmap_step(id) ON DELETE CASCADE
);

CREATE TABLE learning_objective (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_step_id BIGINT NOT NULL,
    objective_key VARCHAR(48) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    importance VARCHAR(16) NOT NULL,
    target_question_count INTEGER NOT NULL,
    objective_order INTEGER NOT NULL,
    CONSTRAINT uk_learning_objective_step_key UNIQUE (roadmap_step_id, objective_key),
    CONSTRAINT uk_learning_objective_step_order UNIQUE (roadmap_step_id, objective_order),
    CONSTRAINT fk_learning_objective_step FOREIGN KEY (roadmap_step_id) REFERENCES learning_roadmap_step(id) ON DELETE CASCADE
);

ALTER TABLE learning_question ADD COLUMN learning_objective_id BIGINT;
ALTER TABLE learning_question ADD CONSTRAINT fk_learning_question_objective
    FOREIGN KEY (learning_objective_id) REFERENCES learning_objective(id) ON DELETE SET NULL;
CREATE INDEX idx_learning_question_objective ON learning_question(learning_objective_id);

CREATE TABLE quality_evaluation_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_type VARCHAR(32) NOT NULL,
    source_key VARCHAR(255),
    model VARCHAR(128),
    prompt_version VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    candidate_count INTEGER NOT NULL DEFAULT 0,
    review_required_count INTEGER NOT NULL DEFAULT 0,
    input_tokens BIGINT,
    output_tokens BIGINT,
    total_tokens BIGINT,
    failure_type VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP
);

CREATE TABLE duplicate_question_pair (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_a_id BIGINT NOT NULL,
    question_b_id BIGINT NOT NULL,
    human_verdict VARCHAR(32),
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_duplicate_question_pair UNIQUE (question_a_id, question_b_id)
);

CREATE TABLE duplicate_evaluation_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    pair_id BIGINT NOT NULL,
    similarity DOUBLE PRECISION NOT NULL,
    embedding_model VARCHAR(128) NOT NULL,
    system_verdict VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_duplicate_result_run_pair UNIQUE (run_id, pair_id)
);

CREATE TABLE objective_evaluation_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    case_type VARCHAR(32) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    reference_key VARCHAR(64),
    reference_title VARCHAR(255),
    importance VARCHAR(16),
    learning_objective_id BIGINT,
    learning_question_id BIGINT,
    ai_verdict VARCHAR(32) NOT NULL,
    ai_confidence DOUBLE PRECISION NOT NULL,
    ai_rationale TEXT NOT NULL,
    human_verdict VARCHAR(32),
    review_status VARCHAR(32) NOT NULL,
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE duplicate_evaluation_dataset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_key VARCHAR(64) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    dataset_version VARCHAR(32) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    embedding_model VARCHAR(128),
    embedding_input_tokens BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    embedded_at TIMESTAMP
);

CREATE TABLE duplicate_evaluation_dataset_sample (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id BIGINT NOT NULL,
    sample_order INTEGER NOT NULL,
    topic VARCHAR(255) NOT NULL,
    question_a TEXT NOT NULL,
    question_b TEXT NOT NULL,
    reference_verdict VARCHAR(32) NOT NULL,
    reference_rationale TEXT NOT NULL,
    embedding_a TEXT,
    embedding_b TEXT,
    similarity DOUBLE PRECISION,
    embedding_model VARCHAR(128),
    reviewer_verdict VARCHAR(32),
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_duplicate_evaluation_dataset_sample UNIQUE (dataset_id, sample_order),
    CONSTRAINT fk_duplicate_evaluation_dataset_sample_dataset FOREIGN KEY (dataset_id)
        REFERENCES duplicate_evaluation_dataset(id)
);

ALTER TABLE learning_quiz ADD COLUMN roadmap_step_id BIGINT;
ALTER TABLE learning_quiz ADD CONSTRAINT fk_learning_quiz_roadmap_step
    FOREIGN KEY (roadmap_step_id) REFERENCES learning_roadmap_step(id) ON DELETE SET NULL;

ALTER TABLE review_schedule ADD COLUMN interval_days INTEGER NOT NULL DEFAULT 1;
ALTER TABLE review_schedule ADD COLUMN repetition_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE review_schedule ADD COLUMN lapse_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE review_schedule ADD COLUMN last_reviewed_at TIMESTAMP;
ALTER TABLE review_schedule ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE review_schedule ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX uk_review_schedule_pending_question ON review_schedule(question_id);

CREATE TABLE review_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_schedule_id BIGINT NOT NULL,
    submission_id UUID NOT NULL,
    selected_answer VARCHAR(255) NOT NULL,
    is_correct BOOLEAN NOT NULL,
    interval_before INTEGER NOT NULL,
    interval_after INTEGER NOT NULL,
    repetition_after INTEGER NOT NULL,
    lapse_after INTEGER NOT NULL,
    status_after VARCHAR(32) NOT NULL,
    reviewed_at TIMESTAMP NOT NULL,
    next_review_at TIMESTAMP,
    CONSTRAINT uk_review_attempt_submission UNIQUE (submission_id),
    CONSTRAINT fk_review_attempt_schedule FOREIGN KEY (review_schedule_id) REFERENCES review_schedule(id)
);

ALTER TABLE source_document ADD COLUMN source_type VARCHAR(16) NOT NULL DEFAULT 'TEXT';
ALTER TABLE source_document ADD COLUMN source_uri VARCHAR(2048);
ALTER TABLE source_document ADD COLUMN original_name VARCHAR(255);
ALTER TABLE source_document ADD COLUMN mime_type VARCHAR(128);
ALTER TABLE source_document ADD COLUMN content_hash VARCHAR(64);
ALTER TABLE source_document ADD COLUMN processing_status VARCHAR(32) NOT NULL DEFAULT 'READY';
ALTER TABLE source_document ADD COLUMN fetched_at TIMESTAMP;
CREATE UNIQUE INDEX uk_source_document_content_hash ON source_document(content_hash);
CREATE INDEX idx_source_document_type_created ON source_document(source_type, created_at);

ALTER TABLE learning_roadmap ADD COLUMN source_document_id BIGINT;
ALTER TABLE learning_roadmap ADD CONSTRAINT fk_learning_roadmap_source_document
    FOREIGN KEY (source_document_id) REFERENCES source_document(id) ON DELETE SET NULL;
CREATE INDEX idx_learning_roadmap_source_document ON learning_roadmap(source_document_id);

CREATE TABLE daily_learning (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learning_date DATE NOT NULL UNIQUE,
    article_title VARCHAR(255) NOT NULL,
    article_url VARCHAR(2048) NOT NULL UNIQUE,
    article_published_at TIMESTAMP,
    article_summary TEXT NOT NULL,
    supplement TEXT NOT NULL,
    concepts TEXT NOT NULL DEFAULT '[]',
    review_topic VARCHAR(255) NOT NULL,
    recommended_review_question_count INTEGER NOT NULL,
    source_document_id BIGINT,
    status VARCHAR(32) NOT NULL,
    completed_at TIMESTAMP,
    generation_error VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_daily_learning_source FOREIGN KEY (source_document_id) REFERENCES source_document(id)
);
CREATE INDEX idx_daily_learning_status_date ON daily_learning(status, learning_date);
ALTER TABLE learning_quiz ADD COLUMN daily_learning_id BIGINT;
ALTER TABLE learning_quiz ADD COLUMN daily_learning_track VARCHAR(32);
ALTER TABLE learning_quiz ADD CONSTRAINT fk_learning_quiz_daily_learning
    FOREIGN KEY (daily_learning_id) REFERENCES daily_learning(id);
CREATE INDEX idx_learning_quiz_daily_learning ON learning_quiz(daily_learning_id, daily_learning_track);
