-- H2는 PostgreSQL pgvector V3를 실행할 수 없다. 학습 흐름 테스트에는 V4~V8의 JPA 스키마만 보완한다.
CREATE TABLE question_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    feedback_type VARCHAR(64) NOT NULL,
    comment VARCHAR(500),
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_question_feedback_question UNIQUE (question_id),
    CONSTRAINT fk_question_feedback_question FOREIGN KEY (question_id) REFERENCES learning_question(id)
);

CREATE TABLE learning_roadmap (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    duration_weeks INTEGER NOT NULL,
    questions_per_week INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    source_type VARCHAR(32) NOT NULL DEFAULT 'WEEKLY',
    description TEXT,
    definition_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE learning_roadmap_week (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id BIGINT NOT NULL,
    week_number INTEGER NOT NULL,
    topic VARCHAR(255) NOT NULL,
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    planned_questions INTEGER NOT NULL,
    CONSTRAINT uk_learning_roadmap_week UNIQUE (roadmap_id, week_number),
    CONSTRAINT fk_learning_roadmap_week_roadmap FOREIGN KEY (roadmap_id) REFERENCES learning_roadmap(id)
);

ALTER TABLE learning_quiz ADD COLUMN roadmap_id BIGINT;
ALTER TABLE learning_quiz ADD CONSTRAINT fk_learning_quiz_roadmap
    FOREIGN KEY (roadmap_id) REFERENCES learning_roadmap(id);

CREATE TABLE learning_roadmap_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id BIGINT NOT NULL,
    step_key VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    topic VARCHAR(255) NOT NULL,
    question_target INTEGER NOT NULL,
    step_order INTEGER NOT NULL,
    CONSTRAINT uk_learning_roadmap_step_key UNIQUE (roadmap_id, step_key),
    CONSTRAINT uk_learning_roadmap_step_order UNIQUE (roadmap_id, step_order),
    CONSTRAINT fk_learning_roadmap_step_roadmap FOREIGN KEY (roadmap_id) REFERENCES learning_roadmap(id)
);

CREATE TABLE learning_roadmap_step_dependency (
    step_id BIGINT NOT NULL,
    prerequisite_step_id BIGINT NOT NULL,
    PRIMARY KEY (step_id, prerequisite_step_id),
    CONSTRAINT fk_roadmap_dependency_step FOREIGN KEY (step_id) REFERENCES learning_roadmap_step(id),
    CONSTRAINT fk_roadmap_dependency_prerequisite FOREIGN KEY (prerequisite_step_id) REFERENCES learning_roadmap_step(id)
);

ALTER TABLE learning_quiz ADD COLUMN roadmap_step_id BIGINT;
ALTER TABLE learning_quiz ADD CONSTRAINT fk_learning_quiz_roadmap_step
    FOREIGN KEY (roadmap_step_id) REFERENCES learning_roadmap_step(id);
