-- H2는 PostgreSQL pgvector V3를 실행할 수 없다. 학습 흐름 테스트에는 V4 이후 JPA 스키마만 보완한다.
CREATE TABLE question_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    feedback_type VARCHAR(64) NOT NULL,
    comment VARCHAR(500),
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_question_feedback_question UNIQUE (question_id),
    CONSTRAINT fk_question_feedback_question FOREIGN KEY (question_id) REFERENCES learning_question(id)
);

CREATE TABLE learning_roadmap (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    duration_weeks INTEGER NOT NULL,
    questions_per_week INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    source_type VARCHAR(32) NOT NULL DEFAULT 'WEEKLY',
    description TEXT,
    definition_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE learning_roadmap_week (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id BIGINT NOT NULL,
    week_number INTEGER NOT NULL,
    topic VARCHAR(255) NOT NULL,
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    planned_questions INTEGER NOT NULL,
    CONSTRAINT uk_learning_roadmap_week UNIQUE (roadmap_id, week_number),
    CONSTRAINT fk_learning_roadmap_week_roadmap FOREIGN KEY (roadmap_id) REFERENCES learning_roadmap(id)
);

ALTER TABLE learning_quiz ADD COLUMN roadmap_id BIGINT;
ALTER TABLE learning_quiz ADD CONSTRAINT fk_learning_quiz_roadmap
    FOREIGN KEY (roadmap_id) REFERENCES learning_roadmap(id);

CREATE TABLE learning_roadmap_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id BIGINT NOT NULL,
    step_key VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    topic VARCHAR(255) NOT NULL,
    question_target INTEGER NOT NULL,
    step_order INTEGER NOT NULL,
    major_topic_key VARCHAR(64) NOT NULL,
    major_topic_title VARCHAR(255) NOT NULL,
    major_topic_description TEXT,
    major_topic_topic VARCHAR(255) NOT NULL,
    subtopic_key VARCHAR(48),
    subtopic_title VARCHAR(255),
    CONSTRAINT uk_learning_roadmap_step_key UNIQUE (roadmap_id, step_key),
    CONSTRAINT uk_learning_roadmap_step_order UNIQUE (roadmap_id, step_order),
    CONSTRAINT fk_learning_roadmap_step_roadmap FOREIGN KEY (roadmap_id) REFERENCES learning_roadmap(id)
);

CREATE TABLE learning_roadmap_step_dependency (
    step_id BIGINT NOT NULL,
    prerequisite_step_id BIGINT NOT NULL,
    PRIMARY KEY (step_id, prerequisite_step_id),
    CONSTRAINT fk_roadmap_dependency_step FOREIGN KEY (step_id) REFERENCES learning_roadmap_step(id),
    CONSTRAINT fk_roadmap_dependency_prerequisite FOREIGN KEY (prerequisite_step_id) REFERENCES learning_roadmap_step(id)
);

ALTER TABLE learning_quiz ADD COLUMN roadmap_step_id BIGINT;
ALTER TABLE learning_quiz ADD CONSTRAINT fk_learning_quiz_roadmap_step
    FOREIGN KEY (roadmap_step_id) REFERENCES learning_roadmap_step(id);

ALTER TABLE review_schedule ADD COLUMN interval_days INTEGER NOT NULL DEFAULT 1;
ALTER TABLE review_schedule ADD COLUMN repetition_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE review_schedule ADD COLUMN lapse_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE review_schedule ADD COLUMN last_reviewed_at TIMESTAMP;
ALTER TABLE review_schedule ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE review_schedule ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX uk_review_schedule_pending_question ON review_schedule(question_id);

CREATE TABLE review_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_schedule_id BIGINT NOT NULL,
    submission_id UUID NOT NULL,
    selected_answer VARCHAR(255) NOT NULL,
    is_correct BOOLEAN NOT NULL,
    interval_before INTEGER NOT NULL,
    interval_after INTEGER NOT NULL,
    repetition_after INTEGER NOT NULL,
    lapse_after INTEGER NOT NULL,
    status_after VARCHAR(32) NOT NULL,
    reviewed_at TIMESTAMP NOT NULL,
    next_review_at TIMESTAMP,
    CONSTRAINT uk_review_attempt_submission UNIQUE (submission_id),
    CONSTRAINT fk_review_attempt_schedule FOREIGN KEY (review_schedule_id) REFERENCES review_schedule(id)
);

ALTER TABLE source_document ADD COLUMN source_type VARCHAR(16) NOT NULL DEFAULT 'TEXT';
ALTER TABLE source_document ADD COLUMN source_uri VARCHAR(2048);
ALTER TABLE source_document ADD COLUMN original_name VARCHAR(255);
ALTER TABLE source_document ADD COLUMN mime_type VARCHAR(128);
ALTER TABLE source_document ADD COLUMN content_hash VARCHAR(64);
ALTER TABLE source_document ADD COLUMN processing_status VARCHAR(32) NOT NULL DEFAULT 'READY';
ALTER TABLE source_document ADD COLUMN fetched_at TIMESTAMP;
CREATE UNIQUE INDEX uk_source_document_content_hash ON source_document(content_hash);
CREATE INDEX idx_source_document_type_created ON source_document(source_type, created_at);

ALTER TABLE learning_roadmap ADD COLUMN source_document_id BIGINT;
ALTER TABLE learning_roadmap ADD CONSTRAINT fk_learning_roadmap_source_document
    FOREIGN KEY (source_document_id) REFERENCES source_document(id) ON DELETE SET NULL;
CREATE INDEX idx_learning_roadmap_source_document ON learning_roadmap(source_document_id);
