CREATE TABLE learning_objective (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_step_id BIGINT NOT NULL REFERENCES learning_roadmap_step(id) ON DELETE CASCADE,
    objective_key VARCHAR(48) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    importance VARCHAR(16) NOT NULL,
    target_question_count INTEGER NOT NULL,
    objective_order INTEGER NOT NULL,
    CONSTRAINT uk_learning_objective_step_key UNIQUE (roadmap_step_id, objective_key),
    CONSTRAINT uk_learning_objective_step_order UNIQUE (roadmap_step_id, objective_order),
    CONSTRAINT ck_learning_objective_importance CHECK (importance IN ('CORE', 'SUPPORTING')),
    CONSTRAINT ck_learning_objective_target CHECK (target_question_count BETWEEN 1 AND 5)
);

CREATE INDEX idx_learning_objective_step_order
    ON learning_objective (roadmap_step_id, objective_order);

ALTER TABLE learning_question
    ADD COLUMN learning_objective_id BIGINT REFERENCES learning_objective(id) ON DELETE SET NULL;

CREATE INDEX idx_learning_question_objective
    ON learning_question (learning_objective_id);
