CREATE TABLE question_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic VARCHAR(255) NOT NULL,
    question_text TEXT NOT NULL,
    question_hash VARCHAR(64) NOT NULL,
    options TEXT,
    correct_answer VARCHAR(255),
    explanation TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_question_history_question_hash UNIQUE (question_hash)
);

CREATE INDEX idx_question_history_topic ON question_history (topic);
