CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keycloak_subject VARCHAR(128) NOT NULL,
    username VARCHAR(128) NOT NULL,
    display_name VARCHAR(255),
    email VARCHAR(320),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_app_user_subject UNIQUE (keycloak_subject),
    CONSTRAINT uk_app_user_username UNIQUE (username)
);

-- 인증을 켜기 전의 로컬 데이터는 기존 로컬 사용자에게 귀속한다. 같은 username으로
-- Keycloak에 최초 로그인하면 애플리케이션이 subject만 교체해 기존 데이터를 이어받는다.
INSERT INTO app_user (keycloak_subject, username, display_name)
VALUES ('local-dev-user', 'eunjuny', 'Local learner');

ALTER TABLE source_document ADD COLUMN owner_id BIGINT REFERENCES app_user(id);
ALTER TABLE source_document ADD COLUMN shared BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE learning_roadmap ADD COLUMN owner_id BIGINT REFERENCES app_user(id);
ALTER TABLE learning_quiz ADD COLUMN owner_id BIGINT REFERENCES app_user(id);

UPDATE source_document SET owner_id = (SELECT id FROM app_user WHERE keycloak_subject = 'local-dev-user');
UPDATE learning_roadmap SET owner_id = (SELECT id FROM app_user WHERE keycloak_subject = 'local-dev-user');
UPDATE learning_quiz SET owner_id = (SELECT id FROM app_user WHERE keycloak_subject = 'local-dev-user');
UPDATE source_document SET shared = TRUE WHERE id IN (SELECT source_document_id FROM daily_learning WHERE source_document_id IS NOT NULL);

ALTER TABLE source_document ALTER COLUMN owner_id SET NOT NULL;
ALTER TABLE learning_roadmap ALTER COLUMN owner_id SET NOT NULL;
ALTER TABLE learning_quiz ALTER COLUMN owner_id SET NOT NULL;

DROP INDEX IF EXISTS uk_source_document_content_hash;
CREATE UNIQUE INDEX uk_source_document_owner_content_hash
    ON source_document (owner_id, content_hash)
    WHERE content_hash IS NOT NULL;
CREATE INDEX idx_source_document_owner_created ON source_document(owner_id, created_at DESC);
CREATE INDEX idx_learning_roadmap_owner_status_created ON learning_roadmap(owner_id, status, created_at DESC);
CREATE INDEX idx_learning_quiz_owner_created ON learning_quiz(owner_id, created_at DESC);

CREATE TABLE daily_learning_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_learning_id BIGINT NOT NULL REFERENCES daily_learning(id) ON DELETE CASCADE,
    owner_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    status VARCHAR(32) NOT NULL DEFAULT 'READY',
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_daily_learning_progress_owner UNIQUE (daily_learning_id, owner_id),
    CONSTRAINT ck_daily_learning_progress_status CHECK (status IN ('READY', 'COMPLETED'))
);

-- 기존 단일 사용자 완료 상태를 사용자별 진행 상태로 이전한다.
INSERT INTO daily_learning_progress (daily_learning_id, owner_id, status, completed_at)
SELECT id,
       (SELECT id FROM app_user WHERE keycloak_subject = 'local-dev-user'),
       status,
       completed_at
FROM daily_learning;

CREATE INDEX idx_daily_learning_progress_owner_status
    ON daily_learning_progress(owner_id, status, daily_learning_id DESC);
