CREATE TABLE source_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE source_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_document_id BIGINT NOT NULL REFERENCES source_document(id) ON DELETE CASCADE,
    chunk_order INTEGER NOT NULL,
    content TEXT NOT NULL,
    CONSTRAINT uk_source_chunk_document_order UNIQUE (source_document_id, chunk_order)
);

CREATE TABLE learning_quiz (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_document_id BIGINT REFERENCES source_document(id) ON DELETE SET NULL,
    topic VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE learning_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT NOT NULL REFERENCES learning_quiz(id) ON DELETE CASCADE,
    question_order INTEGER NOT NULL,
    question_text TEXT NOT NULL,
    options TEXT NOT NULL,
    correct_answer VARCHAR(255) NOT NULL,
    explanation TEXT NOT NULL,
    source_references TEXT,
    CONSTRAINT uk_learning_question_quiz_order UNIQUE (quiz_id, question_order)
);

CREATE TABLE learning_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT NOT NULL REFERENCES learning_quiz(id) ON DELETE CASCADE,
    total_questions INTEGER NOT NULL,
    correct_answers INTEGER NOT NULL,
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE learning_attempt_answer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT NOT NULL REFERENCES learning_attempt(id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL REFERENCES learning_question(id) ON DELETE CASCADE,
    selected_answer VARCHAR(255),
    is_correct BOOLEAN NOT NULL,
    CONSTRAINT uk_learning_attempt_question UNIQUE (attempt_id, question_id)
);

CREATE TABLE review_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES learning_question(id) ON DELETE CASCADE,
    next_review_at TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ai_generation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation VARCHAR(64) NOT NULL,
    model VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    input_tokens BIGINT,
    output_tokens BIGINT,
    total_tokens BIGINT,
    latency_ms BIGINT NOT NULL,
    failure_type VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_learning_quiz_source_document ON learning_quiz (source_document_id);
CREATE INDEX idx_learning_attempt_quiz ON learning_attempt (quiz_id);
CREATE INDEX idx_review_schedule_next_review_at ON review_schedule (next_review_at);
CREATE INDEX idx_ai_generation_log_created_at ON ai_generation_log (created_at);
