CREATE TABLE question_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES learning_question(id) ON DELETE CASCADE,
    feedback_type VARCHAR(64) NOT NULL,
    comment VARCHAR(500),
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_question_feedback_question UNIQUE (question_id)
);

CREATE INDEX idx_question_feedback_status_created
    ON question_feedback (status, created_at DESC);
