CREATE TABLE learning_roadmap (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    duration_weeks INTEGER NOT NULL,
    questions_per_week INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_learning_roadmap_dates CHECK (end_date >= start_date)
);

CREATE TABLE learning_roadmap_week (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id BIGINT NOT NULL REFERENCES learning_roadmap(id) ON DELETE CASCADE,
    week_number INTEGER NOT NULL,
    topic VARCHAR(255) NOT NULL,
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    planned_questions INTEGER NOT NULL,
    CONSTRAINT uk_learning_roadmap_week UNIQUE (roadmap_id, week_number),
    CONSTRAINT ck_learning_roadmap_week_dates CHECK (week_end >= week_start)
);

CREATE INDEX idx_learning_roadmap_status_created
    ON learning_roadmap (status, created_at DESC);
CREATE INDEX idx_learning_roadmap_week_roadmap
    ON learning_roadmap_week (roadmap_id, week_number);
