-- 주차 단위 계획(V5)과 별도로, 선행 단계가 있는 학습 계획을 저장한다.
-- definition_json은 가져온 *.roadmap.json 원본을 재현/감사하기 위한 보관용이며,
-- 실제 진행률 계산은 정규화한 step/dependency 테이블을 기준으로 한다.
ALTER TABLE learning_roadmap
    ADD COLUMN source_type VARCHAR(32) NOT NULL DEFAULT 'WEEKLY',
    ADD COLUMN description TEXT,
    ADD COLUMN definition_json TEXT;

CREATE TABLE learning_roadmap_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id BIGINT NOT NULL REFERENCES learning_roadmap(id) ON DELETE CASCADE,
    step_key VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    topic VARCHAR(255) NOT NULL,
    question_target INTEGER NOT NULL,
    step_order INTEGER NOT NULL,
    CONSTRAINT uk_learning_roadmap_step_key UNIQUE (roadmap_id, step_key),
    CONSTRAINT uk_learning_roadmap_step_order UNIQUE (roadmap_id, step_order),
    CONSTRAINT ck_learning_roadmap_step_target CHECK (question_target > 0)
);

CREATE TABLE learning_roadmap_step_dependency (
    step_id BIGINT NOT NULL REFERENCES learning_roadmap_step(id) ON DELETE CASCADE,
    prerequisite_step_id BIGINT NOT NULL REFERENCES learning_roadmap_step(id) ON DELETE CASCADE,
    PRIMARY KEY (step_id, prerequisite_step_id),
    CONSTRAINT ck_learning_roadmap_step_dependency_distinct CHECK (step_id <> prerequisite_step_id)
);

CREATE INDEX idx_learning_roadmap_step_roadmap_order
    ON learning_roadmap_step (roadmap_id, step_order);
CREATE INDEX idx_learning_roadmap_step_dependency_prerequisite
    ON learning_roadmap_step_dependency (prerequisite_step_id);
