ALTER TABLE review_schedule
    ADD COLUMN interval_days INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN repetition_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN lapse_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN last_reviewed_at TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

-- 기존 데이터에 중복 PENDING 일정이 있어도 최신 한 건만 유지한 뒤 제약을 적용한다.
WITH ranked_pending AS (
    SELECT id,
           ROW_NUMBER() OVER (PARTITION BY question_id ORDER BY created_at DESC, id DESC) AS row_number
    FROM review_schedule
    WHERE status = 'PENDING'
)
UPDATE review_schedule
SET status = 'CANCELLED', updated_at = CURRENT_TIMESTAMP
WHERE id IN (SELECT id FROM ranked_pending WHERE row_number > 1);

CREATE UNIQUE INDEX uk_review_schedule_pending_question
    ON review_schedule (question_id)
    WHERE status = 'PENDING';

CREATE TABLE review_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_schedule_id BIGINT NOT NULL REFERENCES review_schedule(id) ON DELETE CASCADE,
    submission_id UUID NOT NULL,
    selected_answer VARCHAR(255) NOT NULL,
    is_correct BOOLEAN NOT NULL,
    interval_before INTEGER NOT NULL,
    interval_after INTEGER NOT NULL,
    repetition_after INTEGER NOT NULL,
    lapse_after INTEGER NOT NULL,
    status_after VARCHAR(32) NOT NULL,
    reviewed_at TIMESTAMP NOT NULL,
    next_review_at TIMESTAMP,
    CONSTRAINT uk_review_attempt_submission UNIQUE (submission_id)
);

CREATE INDEX idx_review_schedule_status_due
    ON review_schedule (status, next_review_at);
CREATE INDEX idx_review_attempt_schedule_reviewed
    ON review_attempt (review_schedule_id, reviewed_at DESC);
